### ISSUE TITLE
Fatal error: Uncaught ValueError: XMLReader::open(): Argument #1 ($uri) cannot be empty

### ISSUE THREAD

**Issue by BoltUIX** [nuovo/spreadsheet-reader#177]
I tried to upload xlsx 
`Fatal error: Uncaught ValueError: XMLReader::open(): Argument #1 ($uri) cannot be empty in C:\MAMP\htdocs\excel9\library\SpreadsheetReader_XLSX.php:959 Stack trace: #0 C:\MAMP\htdocs\excel9\library\SpreadsheetReader_XLSX.php(959): XMLReader->open('') #1 C:\MAMP\htdocs\excel9\library\SpreadsheetReader.php(238): SpreadsheetReader_XLSX->rewind() #2 C:\MAMP\htdocs\excel9\excelUpload.php(24): SpreadsheetReader->rewind() #3 {main} thrown in C:\MAMP\htdocs\excel9\library\SpreadsheetReader_XLSX.php on line 959`

Here is my full code:
https://coding-zon.blogspot.com/2022/04/import-excel-file-into-mysql-in-php.html

**Comment by Krezalis** [comment]
Discovered problem. When users download XLSX from Google Sheets in xl\workbook.xml we see next items:
`<sheet name="Sheet 1" sheetId="1" state="visible" r:id="rId2"/>`
When we open this file and save in Office Excel its convert to:
`<sheet name="Плахта" sheetId="1" r:id="rId1"/>`

in SpreadsheetReader_XLSX.php:373 we see attrributes filter $Attributes = $Sheet -> attributes('r', true);
so its not correct.

My fix: replace to $Attributes = $Sheet -> attributes();
replace ($Name == 'id') to if ($Name == 'sheetId')
